
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.2
  creationTimestamp: null
  name: globalpolicies.security.everoute.io
spec:
  group: security.everoute.io
  names:
    kind: GlobalPolicy
    listKind: GlobalPolicyList
    plural: globalpolicies
    singular: globalpolicy
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.defaultAction
      name: DefaultAction
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GlobalPolicy allow defines default action of traffics and global
          ip whitelist. Only one GlobalPolicy can exist on kubernetes.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Specification of the desired behavior for this GlobalPolicy.
            properties:
              defaultAction:
                default: Allow
                description: DefaultAction defines global traffic action
                enum:
                - Allow
                - Drop
                type: string
              whitelist:
                description: Whitelist defines IPBlocks than always allow traffics.
                items:
                  description: IPBlock describes a particular CIDR (Ex. "192.168.1.1/24","2001:db9::/64")
                    that is allowed to the pods matched by a NetworkPolicySpec's podSelector.
                    The except entry describes CIDRs that should not be included within
                    this rule.
                  properties:
                    cidr:
                      description: CIDR is a string representing the IP Block Valid
                        examples are "192.168.1.1/24" or "2001:db9::/64"
                      type: string
                    except:
                      description: Except is a slice of CIDRs that should not be included
                        within an IP Block Valid examples are "192.168.1.1/24" or
                        "2001:db9::/64" Except values will be rejected if they are
                        outside the CIDR range
                      items:
                        type: string
                      type: array
                  required:
                  - cidr
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
